### ISSUE TITLE
Location of your .vimrc file?

### ISSUE THREAD

**Issue by dbonner** [mhf-air/u#1]
Hi Tom,
I can't find your .vimrc file, so I can't complete this Installation step:

`modify .vimrc`
`	from my .vimrc, copy the part`
`		augroup u`
`		augroup END`
`	and`
`		function! Format(arg)`
`		endfunction`
`	to your .vimrc for .u file format on save and auto hide import`
All the best,
Daniel

**Comment by mhf-air** [comment]
[My Linux Config File](https://github.com/mhf-air/linux-config-open)

**Comment by dbonner** [comment]
Thanks Tom, Unfortunately, I get the following error every time I open a .u file:

Error detected while processing BufReadPost Autocommands for "*.u"..function u#BeforeRead:
line   12:
E117: Unknown function: prop_type_get
line   13:
E121: Undefined variable: uPropError
E116: Invalid arguments for function empty
line   16:
E117: Unknown function: prop_type_get
line   17:
E121: Undefined variable: uPropWarning
E116: Invalid arguments for function empty
Error detected while processing BufReadPost Autocommands for "*.u"..function u#BeforeRead[24]..u#ToRust:
line   14:
E117: Unknown function: prop_remove

**Comment by dbonner** [comment]
Does it matter that I use zsh?

**Comment by mhf-air** [comment]
From your error message, it seems that your vim version doesn't support text-prop. By the way my vim's version is 9.0.1479. And I don't know if it works under zsh, because I only used bash so far.

**Comment by dbonner** [comment]
Hi Tom, Thanks for the clue about text-prop support.  I was using Neovim, which I have now found out does not support text-prop.  I tried Vim (version 9.0.0000 for Ubuntu Mantic) and now it works without any errors. Thanks again, Daniel.
